version: "3.0"

services:
  ros-container:
    image: bentorobotics/rosbox:robot
    container_name: schaeufele-ros
    privileged: true
    init: true
    restart: always
    network_mode: host
    #environment: ['LD_LIBRARY_PATH=/usr/local/lib/aarch64-linux-gnu/'] # cam won't find libcamera.so on arm64 without this
    environment:
        - EDU_ROBOT_NAMESPACE=schaeufele
    volumes:
      - '/dev:/dev'
      - '/run/udev:/run/udev' # libcamera won't work without this
      - './launch-content:/launch-content:ro'
    working_dir: '/launch-content'
    command: 'ros2 launch schaeufele.launch.py'
