/**:
  ros__parameters:
    format: "MJPEG" # pixel format of streaming buffer
    role: "video"    # stream role (one of {raw, still, video, viewfinder})
    width: 640       # image dimensions
    height: 480      # "
    camera: 1        # camera ID (ID - 1)

# get camera controls:
# `cam --list-controls -cₓ`
#
## Example: ##
# cam --list-controls -c1
# > Control: Brightness: [-1.000000..0.992188]
# > Control: Contrast: [0.569507..4.000000]
#           Name↗                ↖Range

    #Brightness: 0.5
    #Contrast: 4.0
