/**:
  ros__parameters:
    usingPowerManagementBoard: true
    verbosity: false
    canInterface: can2
    frequencyScale: 32
    inputWeight: 0.2
    maxPulseWidth: 100
    timeout: 300
    kp: 0.5
    ki: 40.0
    kd: 0.0
    antiWindup: 1
    responseMode: 0

    controllers: 4

#Flipper vorne
    controller0:
      canID: 1
      gearRatio: 44.0
      encoderRatio: 2048.0
      rpmMax: 204.0
      invertEnc: 1
      doKinematics: false
      drive0:
        channel: 0
      drive1:
        channel: 1

#Flipper hinten
    controller1:
      canID: 0
      gearRatio: 44.0
      encoderRatio: 2048.0
      rpmMax: 204.0
      invertEnc: 1
      doKinematics: false
      drive0:
        channel: 0
      drive1:
        channel: 1

#Ketten vorne 
    controller2:
      canID: 3
      gearRatio: 44.0
      encoderRatio: 2048.0
      rpmMax: 204.0
      invertEnc: 1
      doKinematics: true
      drive0:
        channel: 0
        kinematics: [9.0, 0.0, -9.0]
      drive1:
        channel: 1
        kinematics: [-9.0, 0.0, -9.0]

#Ketten hinten
    controller3:
      canID: 2
      gearRatio: 44.0
      encoderRatio: 2048.0
      rpmMax: 204.0
      invertEnc: 1
      doKinematics: true
      drive0:
        channel: 0
        kinematics: [9.0, 0.0, -9.0]
      drive1:
        channel: 1
        kinematics: [-9.0, 0.0, -9.0]
